# Generated by Django 2.1.1 on 2018-10-04 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ReComment',
        ),
        migrations.AddField(
            model_name='comment',
            name='RecommentId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
